-
  name: 'Icon select editor: icon listing'
  uriPattern: 'api/icon-select-editor/icons'
  defaults:
    '@package': 'Beromir.NeosStudio.IconSelectEditor'
    '@controller': 'Icons'
    '@action': 'index'
    '@format': 'json'
  # The `sources` configuration travels as a query parameter.
  appendExceedingArguments: true
  httpMethods: ['GET']

-
  name: 'Icon select editor: single icon'
  uriPattern: 'api/icon-select-editor/icon'
  defaults:
    '@package': 'Beromir.NeosStudio.IconSelectEditor'
    '@controller': 'Icons'
    '@action': 'icon'
    '@format': 'json'
  # The `resourceUri` travels as a query parameter.
  appendExceedingArguments: true
  httpMethods: ['GET']
